### ISSUE TITLE
Available on CRAN?

### ISSUE THREAD

**Issue by nzbart** [petermeissner/ical#1]
I tried running the installation instructions in the readme i.e. `install.packages("ical")`, but I got an error saying that the package doesn't exist. I also couldn't find it on the CRAN website. What am I doing wrong, or has the package not been published yet?

**Comment by petermeissner** [comment]
You are doing everything right.

The package still waits for approval by CRAN which will hopefully be the case within the week. Until then install.packages will not work but you can install the Github version (its the same that is in process of getting on CRAN at the moment):

```r
if (!require("V8")) {
  install.packages("V8")
}

devtools::install_github("petermeissner/ical")

library(ical)
```

**Comment by nzbart** [comment]
Thanks, Peter. I've installed the package via devtools, and it does exactly what I want.

**Comment by petermeissner** [comment]
👍 Great to hear it works for you!
