### ISSUE TITLE
add location property in ical_parse_df function

### ISSUE THREAD

**Issue by strainel** [petermeissner/ical#3]
Hi

I want to have the location in the data frame created by ical_parse_df.
And I want to get the X-WR-CALNAME property. 

How can I do ? 

Thanks for this package !!

**Comment by petermeissner** [comment]
- I am not sure I understand what you mean by 'location'.
- Currently the only those properties that are available in the data.frame are available. The package does only extract a very small subset of info entailed in the calender-files. There are no plans at the moment to extend the info made available. 
- You may however have a look at the `ical_parser()` function in the package. That is where the parsing and extraction of data takes place: https://github.com/petermeissner/ical/blob/528910e1a98e22198271d96548f722cfa2b6da6b/R/ical_parse.R#L39. If you find your info at the Javascript level we might talk about a pull request. 
- There is another package which is much more potent than ical, you might find a solution there: https://cran.r-project.org/web/packages/calendar/index.html
